# Generated by Django 4.2.6 on 2023-10-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Comedy', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
